import { createApp } from "vue";
import App from "./App";
import router from "./router";
import Antd from "ant-design-vue";
import "ant-design-vue/dist/antd.less";
import "./assets/css/style.less";
const app = createApp(App);
app.use(Antd);
app.use(router);
app.mount("#app");
